In [8]:
import pandas as pd

In [9]:
df = pd.read_csv('/tmp/ab_test/marketing_AB.csv')

In [10]:
df

,Unnamed: 0,user id,test group,converted,total ads,most ads day,most ads hour
0,0,1069124,ad,False,130,Monday,20
1,1,1119715,ad,False,93,Tuesday,22
2,2,1144181,ad,False,21,Tuesday,18
3,3,1435133,ad,False,355,Tuesday,10
4,4,1015700,ad,False,276,Friday,14
...,...,...,...,...,...,...,...
588096,588096,1278437,ad,False,1,Tuesday,23
588097,588097,1327975,ad,False,1,Tuesday,23
588098,588098,1038442,ad,False,3,Tuesday,23
588099,588099,1496395,ad,False,1,Tuesday,23
588100,588100,1237779,ad,False,1,Tuesday,23

In [25]:
# database structure
df.shape
df.dtypes
df.head()

,Unnamed: 0,user id,test group,converted,total ads,most ads day,most ads hour
0,0,1069124,ad,False,130,Monday,20
1,1,1119715,ad,False,93,Tuesday,22
2,2,1144181,ad,False,21,Tuesday,18
3,3,1435133,ad,False,355,Tuesday,10
4,4,1015700,ad,False,276,Friday,14

In [26]:
# Duplicate user ids 
print("Duplicate user ids :", df["user id"].duplicated().sum())

Duplicate user ids : 0

In [29]:
# group sizes
groupSizes = df["test group"].value_counts(dropna=False)
print(groupSizes)

test group
ad     564577
psa     23524
Name: count, dtype: int64

In [30]:
# conversoin distrtibution
print(pd.crosstab(
    df['test group'],
    df['converted'],
    margins = True
))

converted    False   True     All
test group
ad          550154  14423  564577
psa          23104    420   23524
All         573258  14843  588101

In [34]:
df['test group'].value_counts(dropna = False)

test group
ad     564577
psa     23524
Name: count, dtype: int64

In [38]:
# value ranges
print("Minimum ads", df['total ads'].min())
print("Maximum ads", df['total ads'].max())
print("Minimum hour", df['most ads hour'].min())
print("Maximum hour", df['most ads hour'].max())

Minimum ads 1
Maximum ads 2065
Minimum hour 0
Maximum hour 23

In [ ]:
ha